### ISSUE TITLE
Windows USB Installer

### ISSUE THREAD

**Issue by x86fr** [memtest86plus/memtest86plus#35]
I've studied various strategies for the Windows USB Installer. The goal is to create a "universal" bootable USB Flash Drive easily (a Next->Next->OK process is highly desirable), able to boot on BIOS/CSM 32/64 bits or UEFI 32/64 bits. 

Ultimately, I don't want to reinvent the wheel (coding our own installer in C# as originally planned) or using an overkill solution like Rufus (at least right now). Having Memtest86+ as an installation option on Rufus like FreeDOS would be awesome and can be a great solution for the future, but the integration is not as easy as it looks like and we need a quicker solution for early "general" beta-testers.

I will reuse the proven combo Syslinux + NSIS that was used with very few issues on Memtest86+ v4/5 for over 10 years. Of course, I will update both to their latest revision and rework the installer to use the latest NSIS features. All of them are open-source and a specific repo will be created to host the complete files and script.

Syslinux (launched from NSIS) will be used to format the drive and create the bootable partition for BIOS/CSM (with the 32-bit binary by default and a 64-bit option), then both bootx64.efi and bootia32.efi version will be added to the correct directory for UEFI system.

I successfully booted on both BIOS and UEFI with a USB Flash Drive created with this process. The .exe installer is a single file less than 400 KB. Seems a good solution. 😊

**Comment by Fantu** [comment]
I tried a simple/fast dd of the the iso (/usr/lib/memtest86+/memtest86+x64.iso from future debian experimental build) to an usb pendrive and boot/work in both uefi and bios mode. Older like 5.31b instead don't works.
So probably an usb installer I think is not needed anymore but can be enough an howto with what software to use and what do for novice users.
If instead you want something even simpler (download, start, select the drive and run), then a dedicated exe is still need.

**Comment by x86fr** [comment]
dd of the ISO to a pen drive only works on some (very) tolerant BIOS and reduce the initial partition size (that could be hard to recover for the average Joe). On some older systems, even the ISO burned into a CD fail to boot because the actual volume name is not ISO 9660 compliant (patch incoming). :(

dd is probably fine on Linux, but clearly not for Windows users

**Comment by martinwhitaker** [comment]
The ISO construction is based on the method used for the Mageia ISOs, which has been used successfully for many years on a multitude of different systems. On some old buggy BIOSs, changing `-iso_mbr_part_type 0x00` to `-iso_mbr_part_type 0x17` prevents the BIOS going into an infinite loop - we do that for the 32-bit ISOs but not the 64-bit ones. But I'm surprised you say it only works on some very tolerant BIOSs.

**Comment by x86fr** [comment]
The ISO itself is fine on 99% of systems when burned on a CD or used like an ISO via IPMI/VM, except the older ones (2002 and early) which require a ISO 9660 volume name (usually Intel's motherboard). 

What requires a tolerant BIOS is dd'ing the ISO directly to any USB Flash Drive. Maybe I'm unlucky, but that fails on 80+% of my older motherboard here (both on dd from linux or win32diskimager from Windows).

**Comment by debrouxl** [comment]
Are the ISOs you're dd'ing to a USB MSD massaged by `isohybrid` beforehand ? AFAIK, that's supposed to help, at least below 1 GB: when dealing with a > 1024 MB image, isohybrid prints a message about potential incompatibility with some old BIOS.

**Comment by martinwhitaker** [comment]
I think you're unlucky then. The majority of Mageia users use USB flash drives. And this technique has been used since the Mandriva days, so more than 12 years. We do get reports of ISOs not booting or not functioning correctly, but they are almost all solved by getting the user to try another USB stick or another USB port

**Comment by martinwhitaker** [comment]
@debrouxl, no, `isohybrid` is not used. `xorriso` does everything necessary to create hybrid ISOs.

**Comment by x86fr** [comment]
Did some more tests. On an Asus P4P800, burning the ISO with win32diskimager to an old 2GB Flash drive helps. It's now able to boot. On a modern 64GB Flash Drive, a FreeDos burnt with Rufus can boot but not the memtest86+ ISO burnt by win32diskimager. I still have the blinking cursor forever. 

In all cases, the Flash Drive ends up with a 4 MB partition. Most Windows users will ask how to recover the missing space on their flash drive. Linux users are probably more advanced, so the dd procedure is fine.

**Comment by Fantu** [comment]
with rufus should not be choose freedos mode but the dd one (at least in the old version I have, 2.16p)

**Comment by x86fr** [comment]
First release ready here: https://github.com/memtest86plus/windows-installer
Repo will be set public with the first binary beta release.

**Comment by Erquint** [comment]
You mentioned FreeDOS. I'd like to see a binary that would be executable from FreeDOS compiled.
